### ISSUE TITLE
fail to implement npm on nodejs

### ISSUE THREAD

**Issue by conradoGen** [Dashlane/pqc.js#3]
followed the example but failed to use dilithium, is there any nodejs example of the implementation? 

Error [ERR_REQUIRE_ESM]: require() of ES Module xxxxxxxxx/node_modules/@dashlane/pqc-sign-dilithium5-node/dist/sign.js from /home/tconrado/genomica/privacy-relay/dist/main.js not supported.
Instead change the require of sign.js in xxxxxxxxxx/dist/main.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (xxxxxxxxxxx/dist/main.js:7:36) {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by jboillot** [comment]
Hello,
The problem is that your source file has to be an ES module (`"type": "module",` has to appear in your `package.json`). Here is a little demo project that, I hope, will help you: [https://github.com/jboillot/test-dilithium](https://github.com/jboillot/test-dilithium).
Don't hesitate if you have any other question.

**Comment by conradoGen** [comment]
Hello thank your the support, very helpfull!

Due the use of NestJS it was necessary to make a dynamic import following [NestJS ESM import](https://stackoverflow.com/questions/74830166/unable-to-import-esm-module-in-nestjs) 

specifically had to create 2 constants as it returned a premise as follow:

```
import { Injectable } from '@nestjs/common';
import assert from 'node:assert/strict'
@Injectable()
export class DC5Service {
    async dc5Sign() {
        const signBuilder = (await import('@dashlane/pqc-sign-dilithium5-node') ).default;
        const sign = await signBuilder();
        const message = new Uint8Array([0x44, 0x61, 0x73, 0x68, 0x6c, 0x61, 0x6e, 0x65]);       
        const { publicKey, privateKey } = await sign.keypair();
        const { signature } = await sign.sign(message, privateKey);
        const validSignature = await sign.verify(signature, message, publicKey);
        console.log(validSignature)
        assert(validSignature === true);
    }            
}
```
